# Generated by Django 4.0.4 on 2022-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NseDataCoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('underlying', models.CharField(max_length=250)),
                ('changeinOpenInterestPE', models.DecimalField(decimal_places=0, max_digits=50)),
                ('changeinOpenInterestCE', models.DecimalField(decimal_places=0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
