# Generated by Django 4.0.4 on 2022-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsedatacoi',
            name='Diffrence',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
