# Generated by Django 4.0.4 on 2022-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coidata', '0002_nsedatacoi_diffrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpotPrice', models.IntegerField()),
            ],
        ),
    ]
