# Generated by Django 4.0.4 on 2022-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coidata', '0003_spotprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotPrice',
        ),
        migrations.AddField(
            model_name='nsedatacoi',
            name='SpotPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
