# Generated by Django 4.0.4 on 2022-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NSE_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(max_length=250)),
                ('strikePrice', models.BigIntegerField()),
                ('expiryDate', models.DateField()),
                ('openInterest', models.BigIntegerField()),
                ('changeinOpenInterest', models.BigIntegerField()),
                ('totalTradedVolume', models.BigIntegerField()),
                ('underlyingValue', models.BigIntegerField()),
            ],
        ),
    ]
