# Generated by Django 4.0.4 on 2022-05-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nse_data_changeinopeninterest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('one', 'PE'), ('two', 'CE')], max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='nse_data',
            name='strike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.striketype'),
        ),
    ]
