# Generated by Django 4.0.4 on 2022-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_striketype_nse_data_strike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nse_data',
            name='strike',
        ),
        migrations.AddField(
            model_name='nse_data',
            name='name',
            field=models.CharField(choices=[('one', 'PE'), ('two', 'CE')], default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StrikeType',
        ),
    ]
