# Generated by Django 4.0.4 on 2022-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_nse_data_strike_nse_data_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_data',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
