# Generated by Django 4.0.4 on 2022-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_nse_data_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_data',
            name='strikePrice',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
