# Generated by Django 4.0.4 on 2022-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_nse_data_strikeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nse_data',
            name='changeinOpenInterest',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='nse_data',
            name='openInterest',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='nse_data',
            name='totalTradedVolume',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='nse_data',
            name='underlyingValue',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
