# Generated by Django 4.0.4 on 2022-06-09 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_nse_data_changeinopeninterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nse_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nse_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nse_data',
            name='name',
            field=models.CharField(choices=[('PE', 'PE'), ('CE', 'CE')], max_length=250),
        ),
    ]
