# Generated by Django 4.0.4 on 2022-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeRocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.IntegerField()),
                ('underlying', models.CharField(max_length=250)),
                ('changeinOpenInterestPE', models.DecimalField(decimal_places=0, max_digits=50)),
                ('changeinOpenInterestCE', models.DecimalField(decimal_places=0, max_digits=50)),
                ('Diffrence', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Diffrence15Min', models.DecimalField(decimal_places=0, max_digits=20)),
                ('SpotPrice', models.IntegerField()),
                ('oldCE', models.DecimalField(decimal_places=0, max_digits=20)),
                ('oldPE', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
