# Generated by Django 4.0.4 on 2022-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolumeRocker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumerocker',
            name='oldCE',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='volumerocker',
            name='oldPE',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
